source "https://rubygems.org"

# gem "jekyll", "~> 5.0"

gem "github-pages", "~> 232", group: :jekyll_plugins

gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-feed", "~> 0.16"
gem "jekyll-paginate-v2"
gem "jekyll-remote-theme"
gem "faraday-retry"